const Icons = {
    Acceder: require('./Acceder.png'),
    Accepted: require('./Accepted.png'),
    Ajouts: require('./Ajouts.png'),
    Checked: require('./Checked.png'),
    checkedIn: require('./checkedIn.png'),
    closeButton: require('./closeButton.png'),
    Download: require('./Download.png'),
    Fermer: require('./Fermer.png'),
    Filtre: require('./Filtre.png'),
    Gift: require('./Gift.png'),
    Infos: require('./Infos.png'),
    LogOut: require('./Log-out.png'),
    Modifier: require('./Modifier.png'),
    NotChecked: require('./Not-checked.png'),
    notCheckedIn: require('./notCheckedIn.png'),
    Outils: require('./Outils.png'),
    Partager: require('./Partager.png'),
    Participant: require('./Participant.png'),
    PasVu: require('./Pas-vu.png'),
    Paysage: require('./Paysage.png'),
    Portrait: require('./Portrait.png'),
    Print: require('./Print.png'),
    Profil: require('./Profil.png'),
    Rechercher: require('./Rechercher.png'),
    refresh: require('./refresh.png'),
    Refuse: require('./Refuse.png'),
    Rejected: require('./Rejected.png'),
    Retour: require('./Retour.png'),
    Scan: require('./Scan.png'),
    ScanCamera: require('./ScanCamera.png'),
    Supp: require('./Supp.png'),
    totalAttendees: require('./totalAttendees.png'),
    Verifie: require('./Verifie.png'),
    Vu: require('./Vu.png'),
  };
  
  export default Icons;
  